In [2]:
import numpy as np
import random

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 

In [14]:
array_random = np.random.randint(34 , 98 , (4 , 3))

print(f"El array con los números random, cuatro filas y tres columnas ha quedado así: \n {array_random}")
print(f"El número de dimensiones del array son: {array_random.ndim}")
print(f"Los tipos de datos del array son: {array_random.dtype}")

El array con los números random, cuatro filas y tres columnas ha quedado así: 
 [[65 80 83]
 [69 59 88]
 [90 60 45]
 [84 86 68]]
El número de dimensiones del array son: 2
Los tipos de datos del array son: int64


2. Crea tres *arrays* (unidimensional, bidimensional y multidimensional) usando el método `np.array()`. 

In [10]:
# Las listas para crear los *arrays* son las siguientes:

lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]
lista3 = [[[1,2,3],[1,2,3],[1,2,3]]]

print("--------- UNIDIMENSIONAL ---------")
array_uni = np.array(lista1)

print(f"El array unidimensional es: \n {array_uni}")
print(f"La forma del array es: {array_uni.shape}")
print(f"El número de dimensiones del array son: {array_uni.ndim}")
print(f"El número de elementos del array es: {array_uni.size}")
print(f"Los tipos de datos del array son: {array_uni.dtype}")


print("\n--------- BIDIMENSIONAL ---------")
array_bi = np.array(lista2)

print(f"El array bidimensional es: \n {array_bi}")
print(f"La forma del array es: {array_bi.shape}")
print(f"El número de dimensiones del array son: {array_bi.ndim}")
print(f"El número de elementos del array es: {array_bi.size}")
print(f"Los tipos de datos del array son: {array_bi.dtype}")


print("\n--------- TRIDIMENSIONAL ---------")
array_tri = np.array(lista3)

print(f"El array tridimensional es: \n {array_tri}")
print(f"La forma del array es: {array_tri.shape}")
print(f"El número de dimensiones del array son: {array_tri.ndim}")
print(f"El número de elementos del array es: {array_tri.size}")
print(f"Los tipos de datos del array son: {array_tri.dtype}")

--------- UNIDIMENSIONAL ---------
El array unidimensional es: 
 [34 56 71 98 10]
La forma del array es: (5,)
El número de dimensiones del array son: 1
El número de elementos del array es: 5
Los tipos de datos del array son: int64

--------- BIDIMENSIONAL ---------
El array bidimensional es: 
 [[23 45 89 56]
 [12 43 82 44]]
La forma del array es: (2, 4)
El número de dimensiones del array son: 2
El número de elementos del array es: 8
Los tipos de datos del array son: int64

--------- TRIDIMENSIONAL ---------
El array tridimensional es: 
 [[[1 2 3]
  [1 2 3]
  [1 2 3]]]
La forma del array es: (1, 3, 3)
El número de dimensiones del array son: 3
El número de elementos del array es: 9
Los tipos de datos del array son: int64


3. Crea un *array* de todo 0 con tres dimensiones

    Explica el array:
    - ¿Cuántas dimensiones hay? 
    - ¿Qué tamaño tiene?
    - ¿Qué forma tiene?

In [12]:
# Genera un array de 0 con 2 matrices, cada una de ellas con 4 filas y 3 columnas

array_zero = np.zeros((2, 4, 3))

print(f"El array de ceros es: \n {array_zero}")
print(f"La forma del array es: {array_zero.shape}")
print(f"El número de dimensiones del array son: {array_zero.ndim}")
print(f"El número de elementos (tamaño) del array es: {array_zero.size}")

El array de ceros es: 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
La forma del array es: (2, 4, 3)
El número de dimensiones del array son: 3
El número de elementos (tamaño) del array es: 24


4. Crea un *array* vacío de 2 x 5 X 4. 

    - ¿Qué valores nos han salido en el *array*?  

    - ¿Por qué nos salen esos valores? 

In [18]:
array_vacio = np.empty((2 , 5 , 4))

print(f"El array de vacío es: \n {array_vacio}")
print(f"\nDado que el método `np.empty` crea un *array* vacío sin inicializar sus elementos, significa que los valores de los elementos pueden ser impredecibles y dependerán de los datos almacenados previamente en la memoria.")

El array de vacío es: 
 [[[4.64307850e-310 0.00000000e+000 6.94650644e-310 6.94650646e-310]
  [6.94650667e-310 6.94650669e-310 6.94650669e-310 6.94650645e-310]
  [6.94650725e-310 6.94650719e-310 6.94650645e-310 6.94650725e-310]
  [6.94650725e-310 6.94650725e-310 6.94650725e-310 6.94650724e-310]
  [6.94650726e-310 6.94650645e-310 6.94650646e-310 6.94650644e-310]]

 [[6.94650676e-310 6.94650726e-310 6.94650645e-310 6.94650722e-310]
  [6.94650669e-310 6.94650683e-310 6.94650669e-310 6.94650717e-310]
  [6.94650644e-310 6.94650725e-310 6.94650676e-310 6.94650645e-310]
  [6.94650727e-310 6.94650710e-310 6.94650644e-310 6.94650646e-310]
  [6.94650724e-310 6.94650669e-310 6.94650644e-310 6.94650726e-310]]]

Dado que el método `np.empty` crea un *array* vacío sin inicializar sus elementos, significa que los valores de los elementos pueden ser impredecibles y dependerán de los datos almacenados previamente en la memoria.


5. En este ejercicio vamos a crear dos *arrays*:

    - Un *array* tridimensional 5x2x3 con todos los valores iguales a 1.


    - Un *array* tridimensional de 2 x 3 x 5  con números aleatorios entre 0-1


    Intenta sumarlos entre ellos. ¿Puedes? ¿Por qué? 

In [23]:
array_unos = np.ones((5 , 2 , 3))
print(f"El array de unos es: \n {array_unos}")

array_aleatorio = np.random.rand(2 , 3 , 4)
print(f"\nEl array aleatorio del 0 al 1 es: \n {array_aleatorio}")


try:
    suma = np.add(array_unos , array_aleatorio)
except:
    print(f"\nNo se ha podido sumar ambos arrays ya que sus dimensiones son diferentes: uno es de tamaño 5x2x3 y el otro es 2x3x5")

El array de unos es: 
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

El array aleatorio del 0 al 1 es: 
 [[[0.13937118 0.21976729 0.10895996 0.07391135]
  [0.93197194 0.64117279 0.22732802 0.67937108]
  [0.46198254 0.44378195 0.44300681 0.36432627]]

 [[0.84577309 0.03540046 0.14530908 0.91526716]
  [0.79587425 0.31333198 0.40886771 0.98949274]
  [0.62691072 0.3210469  0.12344357 0.38710599]]]

No se ha podido sumar ambos arrays ya que sus dimensiones son diferentes: uno es de tamaño 5x2x3 y el otro es 2x3x5


6. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8(incluido). 

In [41]:
array_50 = np.arange(50)

print(f"El array unidimensional de 50 elementos es: \n{array_50}")
print(f"El primer elemento es: {array_50[0]}")
print(f"Todos los elementos en posición impar del array son: {array_50[1::2]}")
print(f"Los cuatro primeros elementos son: {array_50[:4]}")
print(f"Los últimos tres elementos son: {array_50[-3:]}")
print(f"Los elementos entre el 4 y el 8 (incluido) son: {array_50[4:9]}")

El array unidimensional de 50 elementos es: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
El primer elemento es: 0
Todos los elementos en posición impar del array son: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Los cuatro primeros elementos son: [0 1 2 3]
Los últimos tres elementos son: [47 48 49]
Los elementos entre el 4 y el 8 (incluido) son: [4 5 6 7 8]


7. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.

In [39]:
array_bi_2 = np.random.randint(5 , 20 , (4 , 5))

print(f"El array bidimensional es: \n{array_bi_2}")

El array bidimensional es: 
[[18 10 18 14  8]
 [ 7  7  6  9 17]
 [ 5 15  6 14 14]
 [12  7  5 10 16]]


In [44]:
print(f"La primera fila y todas las columnas del array: {array_bi_2[0]}")
print(f"Todas las filas pares: {array_bi_2[::2]}")
print(f"La primera columna y todas las filas: {array_bi_2[: , 0]}")

La primera fila y todas las columnas del array: [18 10 18 14  8]
Todas las filas pares: [[18 10 18 14  8]
 [ 5 15  6 14 14]]
La primera columna y todas las filas: [18  7  5 12]


8. Crea una matriz multidimensional de 2 x 3 x 5 de unos y haz una copia de la matriz multidimensional. 


    - Reemplaza los siguientes valores:

        - Array 1, fila 2, columna 3 por 100
        
        - Array 2, fila 1, columna 4 por 100
        
        - Array 1, fila 3, columna 2 por 100
        
        - Array 2, fila 2, columna 1 por 100


    - Haz una copia de la matriz anterior. Crea una matriz de 1 de 5 x 2 x 3 e intenta sumarla a la copia. ¿Se puede?  ¿Por qué?


    - Trata de modificar las dimensiones de tu matriz de unos para poder sumarla con la copia. Hazlo de las dos formas:

        - `transpose`
        
        - `reshape`
        
    - Vuelve a intentar sumar las dos matrices

In [49]:
array_unos_2 = np.ones((2, 3, 5))
print(f"Array original:\n {array_unos_2}")


copia_array = array_unos_2.copy()
print(f"\nCopia de la matriz original:\n{copia_array}")

# Reemplaza los valores:
array_unos_2[0, 1, 2] = 100  
copia_array[1, 0, 3] = 100  
array_unos_2[0, 2, 1] = 100  
copia_array[1, 1, 0] = 100  

print(f"\nArray original con valores modificados:\n {array_unos_2}")
print(f"\nCopia de la matriz original con valores modificados:\n{copia_array}")

# Al intentar sumar esta matriz dará el mismo error que en el ejercicio 5 porque las dimensiones no coinciden
array_unos_3 = np.ones((5, 2, 3))

# Modifica las dimensiones de la matriz de unos con TRANSPOSE
array_unos_3_transp = np.transpose(array_unos_3, (1, 2, 0))
print(f"\nResultado de la suma usando transpose:\n{np.add(copia_array , array_unos_3_transp)}")

# Modifica las dimensiones de la matriz de unos con RESHAPE
array_unos_3_reshaped = array_unos_3.reshape(2, 3, 5)
print(f"\nResultado de la suma usando reshape:\n{np.add(copia_array , array_unos_3_reshaped)}")




Array original:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Copia de la matriz original:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Array original con valores modificados:
 [[[  1.   1.   1.   1.   1.]
  [  1.   1. 100.   1.   1.]
  [  1. 100.   1.   1.   1.]]

 [[  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]]]

Copia de la matriz original con valores modificados:
[[[  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]]

 [[  1.   1.   1. 100.   1.]
  [100.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.]]]

Resultado de la suma usando transpose:
[[[  2.   2.   2.   2.   2.]
  [  2.   2.   2.   2.   2.]
  [  2.   2.   2.   2.   2.]]

 [[  2.   2.   2. 101.   2.]
  [101.   2.   2.   2.   2.]
  [  2.   2.   2.   2.   2.]]]

Resultado de la suma usando reshape:
[[[  2.  

9. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional o multidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

In [57]:
array_random_2 = np.random.randint(0 , 100 , (3 , 4))
print(f"Array random:\n {array_random_2}")

Array random:
 [[63  6 91  4]
 [98 59 77 74]
 [81 77 74 18]]


In [61]:
media_el = np.mean(array_random_2)
print(f"La media de todos los elementos del array es:\n {media_el}")

media_col = np.round(np.mean(array_random_2 , axis = 0) , 2)
print(f"\nLa media de los elementos de las columnas es:\n {media_col}")

max_fila = np.max(array_random_2 , axis = 1)
print(f"\nEl valor máximo de cada fila es:\n {max_fila}")

min_fila = np.min(array_random_2 , axis = 1)
print(f"\nEl valor mínimo de cada fila es:\n {min_fila}")

mascara = array_random_2 > 90
print(f"\nLos datos mayores de 90 son:\n {array_random_2[mascara]}") 
print(f"Y se encuentran en:\n {np.where(array_random_2 > 90)}") 

print(f"\nEl array ordenado de mayor a menor es:\n{-np.sort(-array_random_2)}")



La media de todos los elementos del array es:
 60.166666666666664

La media de los elementos de las columnas es:
 [80.67 47.33 80.67 32.  ]

El valor máximo de cada fila es:
 [91 98 81]

El valor mínimo de cada fila es:
 [ 4 59 18]

Los datos mayores de 90 son:
 [91 98]
Y se encuentran en:
 (array([0, 1]), array([2, 0]))

El array ordenado de mayor a menor es:
[[91 63  6  4]
 [98 77 74 59]
 [81 77 74 18]]
